### ISSUE TITLE
Ungraceful termination, exemplified by cpp-demo

### ISSUE THREAD

**Issue by youph** [NICTA/stateline#47] opened 2015-07-21 02:18 UTC
When I run the cpp demo as
```
./stateline --config=cpp-demo-config.json
```
the server works (i.e., produces the chains), but terminates with an ugly failure message:
```
...
I0721 12:16:32.234241 12025 router.cpp:75] Router main's Poll thread has exited loop, must be shutting down
F0721 12:16:32.440459 12029 thread.hpp:21] Exception thrown in child thread: Context was terminated
*** Check failure stack trace: ***
    @     0x7f5596d9fa0d  google::LogMessage::Fail()
    @     0x7f5596da18c0  google::LogMessage::SendToLog()
    @     0x7f5596d9f5d2  google::LogMessage::Flush()
    @     0x7f5596da22de  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f559700a270  _ZZN9stateline13startInThreadINS_5comms15ServerHeartbeatEISt17reference_wrapperIN3zmq9context_tEES3_IKNS1_17HeartbeatSettingsEEEEESt6futureIbERbDpOT0_ENKUlOS6_OS9_E_clESG_SH_
    @     0x7f559700906e  std::_Function_handler<>::_M_invoke()
    @     0x7f5596fea7c2  std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f559665f36b  __pthread_once_slow
    @     0x7f559700f975  _ZNSt6thread5_ImplISt12_Bind_simpleIFZNSt13__future_base17_Async_state_implIS1_IFZN9stateline13startInThreadINS4_5comms15ServerHeartbeatEJSt17reference_wrapperIN3zmq9context_tEES8_IKNS6_17HeartbeatSettingsEEEEESt6futureIbERbDpOT0_EUlOSB_OSE_E_SB_SE_EEbEC4EOSP_EUlvE_vEEE6_M_runEv
    @     0x7f5596b3fe30  (unknown)
    @     0x7f55966586aa  start_thread
    @     0x7f559638deed  (unknown)
Aborted (core dumped)
```

And the worker disconnects from the server without throwing any error messages.
Is this a 'normal' behaviour?

**Comment by lmccalman** [comment] 2015-07-21 03:22
This is caused by not catching the exception thrown upon deleting context (which is the correct way to shut down zmq in this case). The message is ugly, but it's not really an error. Fix should be simple, but you can keep using it as normal.

**Comment by ltiao** [comment] 2015-08-25 13:42
Duplicate of #29

**Closed by ltiao** 2015-08-25 13:42 UTC
Labels: bug
